# Generated by Django 6.0.1 on 2026-02-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_color',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
