# Generated by Django 6.0.1 on 2026-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='question',
            field=models.TextField(help_text='helptext', max_length=200),
        ),
    ]
