# Generated by Django 6.0.1 on 2026-02-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0007_tag_joke_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='tag',
        ),
        migrations.AddField(
            model_name='joke',
            name='tags',
            field=models.ManyToManyField(to='jokes.tag'),
        ),
    ]
